///////////////////////////////////////////////////////////////////////////////
// GameSpy ATLAS Competition System Header File
//
// NOTE: This is an auto-generated file, do not edit this file directly.
///////////////////////////////////////////////////////////////////////////////

#ifndef _ATLAS_TAPRACE_V2_H_
#define _ATLAS_TAPRACE_V2_H_

#ifdef __cplusplus
extern "C" {
#endif

extern int ATLAS_GET_KEY(char* keyName);
extern char* ATLAS_GET_KEY_NAME(int keyId);
extern int ATLAS_GET_STAT(char* statName);
extern char* ATLAS_GET_STAT_NAME(int statId);
extern int ATLAS_GET_STAT_PAGE_BY_ID(int statId);
extern int ATLAS_GET_STAT_PAGE_BY_NAME(char* statName);

#define ATLAS_RULE_SET_VERSION 2

// KEYS
// Use these key ID's to report match data for your game.

#define RACE_TIME 1  // [TYPE: int] [DESC: Player's race time for the match (milliseconds).]
#define KEY_NICK 2  // [TYPE: string] [DESC: Player's nickname to report]
#define KEY_LATITUDE 3  // [TYPE: float]
#define KEY_LONGITUDE 4  // [TYPE: float]
#define KEY_MULTI_PLAY 5  // [TYPE: int] [DESC: Key for setting multi-player match stats. Set to 1 if yes; otherwise zero]
#define KEY_SINGLE_PLAY 6  // [TYPE: int] [DESC: Key for setting single player game stats. Set to 1 if yes; otherwise zero]
#define SP_RACE_TIME 7  // [TYPE: int] [DESC: Player's race time for the match (milliseconds).]
#define KEY_RACE_DATE_TIME 8  // [TYPE: string] [DESC: Date/Time of last single play or match for a player]

///////////////////////////////////////////////////////////////////////////////

// STATS
// Use these stat ID's to query aggregate statistics for your game.

#define AVERAGE_RACE_TIME 6  // [TYPE: float] [DESC: Player's average race time per match (milliseconds/match).]
#define BEST_RACE_TIME 3  // [TYPE: int] [DESC: Player's career best match race time (milliseconds).]
#define CAREER_DISCONNECTS 10  // [TYPE: int] [DESC: Player's total number of times match disconnected.]
#define CAREER_DRAWS 12  // [TYPE: int] [DESC: Player's total number of draws (tied matches).]
#define CAREER_LONGEST_DRAW_STREAK 16  // [TYPE: int] [DESC: Player's longest streak of matches tied]
#define CAREER_LONGEST_LOSS_STREAK 15  // [TYPE: int] [DESC: Player's longest streak of matches loss]
#define CAREER_LONGEST_WIN_STREAK 14  // [TYPE: int] [DESC: Player's longest streak of matches won]
#define CAREER_LOSSES 2  // [TYPE: int] [DESC: Player's number of matches loss]
#define CAREER_WINS 1  // [TYPE: int] [DESC: Player's number of matches won]
#define CURRENT_DRAW_STREAK 13  // [TYPE: int] [DESC: Player's current streak of matches tied]
#define CURRENT_LOSS_STREAK 8  // [TYPE: int] [DESC: Player's current streak of matches loss]
#define CURRENT_WIN_STREAK 7  // [TYPE: int] [DESC: Player's current streak of matches won]
#define DISCONNECT_RATE 11  // [TYPE: float] [DESC: Player's disconnect rate (disconnects/matches).]
#define LAST_TIME_PLAYED 26  // [TYPE: string] [DESC: Date/Time of last single play or match for a player]
#define LATITUDE 19  // [TYPE: float] [DESC: Latitude for Player's location after a single or multiplayer game]
#define LONGITUDE 20  // [TYPE: float] [DESC: Longitude for a Player's location after a single or multiplayer game]
#define NICK 18  // [TYPE: string] [DESC: Player's nickname for leaderboard]
#define SP_AVERAGE_RACE_TIME 24  // [TYPE: float] [DESC: Player's average race time per single plays (milliseconds/play).]
#define SP_BEST_RACE_TIME 21  // [TYPE: int] [DESC: Player's career best match race time (milliseconds).]
#define SP_TOTAL_PLAYS 23  // [TYPE: int] [DESC: Total number of single plays that were completed]
#define SP_TOTAL_RACE_TIME 25  // [TYPE: int] [DESC: Player's total race time for all simgle plays (milliseconds).]
#define SP_WORST_RACE_TIME 22  // [TYPE: int] [DESC: Player's career worst single play time (milliseconds).]
#define TOTAL_COMPLETE_MATCHES 17  // [TYPE: int] [DESC: Total number of matches where the game went to completion (all win/loss/draw results).]
#define TOTAL_MATCHES 5  // [TYPE: int] [DESC: Total number of matches that were completed]
#define TOTAL_RACE_TIME 9  // [TYPE: int] [DESC: Player's total race time for all matches (milliseconds).]
#define WORST_RACE_TIME 4  // [TYPE: int] [DESC: Player's career worst match time (milliseconds).]


#ifdef __cplusplus
}
#endif

#endif // _ATLAS_TAPRACE_V2_H_
