# NAT Negotiation SDK Makefile
# Copyright 2004-2009 GameSpy Industries

TARGET=natneg
THREADS=yes
DEBUG=no
CFLAGS=

SRC = \
	../../../darray.c\
	../../../common/gsAssert.c\
	../../../common/gsAvailable.c\
	../../../common/gsPlatform.c\
	../../../common/gsPlatformSocket.c\
	../../../common/gsPlatformThread.c\
	../../../common/gsPlatformUtil.c\
	../../../common/gsStringUtil.c\
	../../../common/gsDebug.c\
	../../../common/gsMemory.c\
	../../../common/linux/LinuxCommon.c\
	../../natneg.c\
	../../NATify.c\
	../simpletest.c

include ../../../common/linux/Makefile.common
