macro(MFC_Stage1)
    if(WIN32 OR "${CMAKE_SYSTEM_NAME}" MATCHES "Windows" OR MINGW OR CYGWIN)
        if (UNISPY_MSVC_STATIC)
            set(CMAKE_MFC_FLAG 1)
        else()
            set(CMAKE_MFC_FLAG 2)
        endif()
    endif()
endmacro()

macro(MFC_Stage2 proj)
    if(WIN32 OR "${CMAKE_SYSTEM_NAME}" MATCHES "Windows" OR MINGW OR CYGWIN)
        if (NOT UNISPY_MSVC_STATIC)
            target_compile_definitions(${proj} PRIVATE _AFXDLL)
        endif()

        if (UNISPY_COMPILER_MSVC)
            target_link_options(${proj} PRIVATE /SUBSYSTEM:WINDOWS)
        endif()
    endif()
endmacro()
