///////////////////////////////////////////////////////////////////////////////
// GameSpy ATLAS Competition System Source File
//
// NOTE: This is an auto-generated file, do not edit this file directly.
///////////////////////////////////////////////////////////////////////////////

#include "atlas_atlasSamples_v2.h"


const char * ATLAS_KEY_NAMES[] = 
{
	"",
	"RACE_TIME_P",
	"USED_VEHICLE_1_P",
	"USED_VEHICLE_2_P",
	"USED_VEHICLE_1_G",
	"USED_VEHICLE_2_G",
	"USED_TRACK_1",
	"USED_TRACK_2",
	"PLAYER_NAME_P"
};

///////////////////////////////////////////////////////////////////////////////

const char * ATLAS_STAT_NAMES[] = 
{
	"",
	"NUM_CAREER_RACES",
	"NUM_CAREER_WINS",
	"NUM_CAREER_LOSSES",
	"WIN_LOSS_RATIO",
	"CURRENT_WIN_STREAK",
	"CURRENT_LOSS_STREAK",
	"LONGEST_WIN_STREAK",
	"LONGEST_LOSS_STREAK",
	"TOTAL_RACING_TIME",
	"BEST_RACE_TIME",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED",
	"TOTAL_NUM_RACES",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED",
	"PLAYER_NAME",
	"PLAYER_NAME",
	"PLAYER_NAME",
	"PLAYER_NAME",
	"PLAYER_NAME"
};

///////////////////////////////////////////////////////////////////////////////

// STAT ID to CATEGORY NAME MAP

const char * ATLAS_STAT_CATEGORY_NAMES[] = 
{
	"",
	"Player_Stats",
	"Player_Stats",
	"Player_Stats",
	"Player_Stats",
	"Player_Stats",
	"Player_Stats",
	"Player_Stats",
	"Player_Stats",
	"Player_Stats",
	"Player_Stats",
	"Vehicle_1",
	"Vehicle_1",
	"Track_1",
	"Track_1",
	"Game_Stats",
	"Vehicle_2",
	"Vehicle_2",
	"Track_2",
	"Track_2",
	"Player_Stats",
	"Vehicle_1",
	"Vehicle_2",
	"Track_1",
	"Track_2"
};

///////////////////////////////////////////////////////////////////////////////


